---
abstract: ~
author:
  - 'Ash Berlin C<< <ash@cpan.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mechanize-TreeBuilder
no_index:
  directory:
    - inc
    - t
    - t/lib
requires:
  HTML::TreeBuilder: 0
  Moose: 0.65
  MooseX::Role::Parameterized: 0
  Scalar::Util: 0
  Test::WWW::Mechanize: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.10000
