--- 
abstract: ~
author: Ash Berlin C<< <ash@cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Mechanize-TreeBuilder
no_index: 
  directory: 
    - t/lib
    - inc
    - t
recommends: 
  HTML::TreeBuilder: 0
requires: 
  Moose: 0
  Test::WWW::Mechanize: 0
  perl: 5.8.1
version: 1
